//Angeles Gómez Jesús Gerardo
//Peñafiel Hernández José Manuel
//Ramírez Serna Brayan Emmanuel
package Paquete_Vistas;

import Paquete_Modelo.RegistroActasConstitutivas;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;
/**

/**
 *
 * @author jesma
 */
public class ActasConsRegistro extends javax.swing.JFrame {
    private final RegistroActasConstitutivas RAC;
    
   

    /**
     * Creates new form RegistroSociedad
     */
    public ActasConsRegistro() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Paquete_Imagenes/128Logo.png")).getImage());
        this.setLocationRelativeTo(null);
        RAC = new RegistroActasConstitutivas();
        listar();
        limpiar();
        
    }
    
    public void listar()
    {
        tbActasConst.setModel(RAC.getDatos());
    }
    
    public void limpiar()
    {
        txtNumeroDePoliza.setText("");
        txtNoDeFojas.setText("");
        cbxLibro.setSelectedIndex(0);
        cbxLicenciado.setSelectedIndex(0);
        cbxCorredor.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroDePoliza = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNoDeFojas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxLibro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxLicenciado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbxCorredor = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnAtras = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbActasConst = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Actas Constitutivas");

        jPanel1.setForeground(new java.awt.Color(232, 232, 232));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registrar Actas Constitutivas");

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Completa la siguiente información");

        jLabel3.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Número de Póliza:");

        txtNumeroDePoliza.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtNumeroDePoliza.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroDePoliza.setToolTipText("Número de Póliza de la Acta Constitutiva a registrar");
        txtNumeroDePoliza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroDePolizaFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Número de Fojas");

        txtNoDeFojas.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtNoDeFojas.setForeground(new java.awt.Color(0, 0, 0));
        txtNoDeFojas.setToolTipText("Número de fojas de la Acta Constitutiva a registrar");
        txtNoDeFojas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoDeFojasFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Número de Libro:");

        cbxLibro.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cbxLibro.setForeground(new java.awt.Color(0, 0, 0));
        cbxLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbxLibro.setToolTipText("Libro donde se guardara la Acta Constitutiva a registrar");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/ActasConstitutivasForm.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Licenciado:");

        cbxLicenciado.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cbxLicenciado.setForeground(new java.awt.Color(0, 0, 0));
        cbxLicenciado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Maria Gabriela Gomez Rubio", "Karen Estefania Garcia Cruz", "Norberta Ruiz Salinas", "Juan Carlos Padilla Sanchez", "Luis Fernando Roldan Arellano", "Sergio Perez Grovas" }));
        cbxLicenciado.setToolTipText("Licenciado encargado de redatcar la Acta Constitutiva a registrar");

        jLabel9.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Corredor:");

        cbxCorredor.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cbxCorredor.setForeground(new java.awt.Color(0, 0, 0));
        cbxCorredor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Eduardo Javier Baños Gomez", "Alberto Mendez Llaca", "Maria Rebeca Cruz Bustos", "Jose Rafael Lugo Bastida", "Carlos Francisco Herrera Arriaga" }));
        cbxCorredor.setToolTipText("Corredor encargado de firmar la Acta Constitutiva a registrar");

        btnGuardar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/GuardarBtn.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/ActualizarBtn.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/AtrasBtn.png"))); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(190, 190, 190)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 240, Short.MAX_VALUE)
                                    .addComponent(btnActualizar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNoDeFojas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                            .addComponent(txtNumeroDePoliza, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel4))
                                    .addGap(161, 161, 161)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnGuardar)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9)
                                            .addComponent(cbxLicenciado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbxCorredor, 0, 1, Short.MAX_VALUE))))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btnAtras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroDePoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLicenciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoDeFojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar))
                .addGap(101, 101, 101))
        );

        tbActasConst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbActasConst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbActasConstMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbActasConst);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroDePolizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroDePolizaFocusLost

    }//GEN-LAST:event_txtNumeroDePolizaFocusLost

    private void txtNoDeFojasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoDeFojasFocusLost
        
    }//GEN-LAST:event_txtNoDeFojasFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int res = 0;
        int noPoliza = 0, noDeFojas = 0, idLicenciado = 0, idCorredor = 0;
        String noDePolizaS = null, noDeFojasS = null;
        boolean banderaPoliza = true, banderaFojas = true;
        
        noDePolizaS = txtNumeroDePoliza.getText();
        try
        {
            noPoliza = Integer.parseInt(noDePolizaS);
        }
        catch (NumberFormatException e)
        {
            banderaPoliza = false;
        }
        if(banderaPoliza && (noPoliza) < 1)
            banderaPoliza = false;
        
        noDeFojasS = txtNoDeFojas.getText();
        try
        {
            noDeFojas = Integer.parseInt(noDeFojasS);
        }
        catch (NumberFormatException e)
        {
            banderaFojas = false;
        }
        if(banderaFojas && (noDeFojas) < 1)
            banderaFojas = false;
        

        
        int noLibro = 0;
        boolean banderaLibro = true;
        if(cbxLibro.getSelectedIndex() == 0)
            banderaLibro = false;
        else
            noLibro = cbxLibro.getSelectedIndex();
        
        boolean banderaLicenciado = true;
        if(cbxLicenciado.getSelectedIndex() == 0)
            banderaLicenciado = false;
        else
            idLicenciado = cbxLicenciado.getSelectedIndex();
        
        boolean banderaCorredor = true;
        if(cbxCorredor.getSelectedIndex() == 0)
            banderaCorredor = false;
        else
            idCorredor = cbxCorredor.getSelectedIndex();
        
        String errores[] = {" Número de Póliza ", " Número de fojas ", " Número de Libro ", " Licenciado ", " Corredor "};
        String verificar = "Favor de Verificar los siguientes campos: ";
        if(banderaPoliza && banderaFojas && banderaLibro && banderaLicenciado && banderaCorredor)
        {
            res = RAC.insertarDatos(noPoliza, noDeFojas, noLibro, idLicenciado, idCorredor);
            if (res > 0)
            {
                listar();
                limpiar();
                this.setVisible(false);
                RegistroSociedad rs = new RegistroSociedad();
                rs.setVisible(true);                
            }
        }
        else
        {
            if(!banderaPoliza)
            {
                txtNumeroDePoliza.setText("");
                verificar+="-" + errores[0];
            }
            if (!banderaFojas)
            {
                txtNoDeFojas.setText("");
                verificar += "-" + errores[1];
            }
            if (!banderaLibro)
                verificar += "-" + errores[2];
            if(!banderaLicenciado)
                verificar += "-" + errores[3];
            if(!banderaCorredor)
                verificar += "-" + errores[4];
            
            JOptionPane.showMessageDialog(null, verificar, "Error Registro", 1);
        }        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tbActasConstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbActasConstMouseClicked
        int row = tbActasConst.getSelectedRow(); 
        
        txtNumeroDePoliza.setText(tbActasConst.getValueAt(row, 0).toString());
        txtNoDeFojas.setText(tbActasConst.getValueAt(row, 1).toString());
        
        cbxLibro.setSelectedItem(tbActasConst.getValueAt(row, 2).toString());
        cbxLicenciado.setSelectedItem(tbActasConst.getValueAt(row,3).toString());
        cbxCorredor.setSelectedItem(tbActasConst.getValueAt(row,4).toString());
    }//GEN-LAST:event_tbActasConstMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int row = -1;
        row = tbActasConst.getSelectedRow();
        if(row < 0)
            JOptionPane.showMessageDialog(null, "Favor de seleccionar un registro", "Actualizar datos", -1);
        else
        {
            int res = 0;
            int noPoliza = 0, noDeFojas = 0, idLicenciado = 0, idCorredor = 0;
            String noDePolizaS = null, noDeFojasS = null;
            boolean banderaPoliza = true, banderaFojas = true;

            noDePolizaS = txtNumeroDePoliza.getText();
            try
            {
                noPoliza = Integer.parseInt(noDePolizaS);
            }
            catch (NumberFormatException e)
            {
                banderaPoliza = false;
            }
            if(banderaPoliza && (noPoliza) < 1)
                banderaPoliza = false;

            noDeFojasS = txtNoDeFojas.getText();
            try
            {
                noDeFojas = Integer.parseInt(noDeFojasS);
            }
            catch (NumberFormatException e)
            {
                banderaFojas = false;
            }
            if(banderaFojas && (noDeFojas) < 1)
                banderaFojas = false;

            int noLibro = 0;
            boolean banderaLibro = true;
            if(cbxLibro.getSelectedIndex() == 0)
                banderaLibro = false;
            else
                noLibro = cbxLibro.getSelectedIndex();

            boolean banderaLicenciado = true;
            if(cbxLicenciado.getSelectedIndex() == 0)
                banderaLicenciado = false;
            else
                idLicenciado = cbxLicenciado.getSelectedIndex();

            boolean banderaCorredor = true;
            if(cbxCorredor.getSelectedIndex() == 0)
                banderaCorredor = false;
            else
                idCorredor = cbxCorredor.getSelectedIndex();

            String errores[] = {" Número de Póliza ", " Número de fojas ", " Número de Libro ", " Licenciado ", " Corredor "};
            String verificar = "Favor de Verificar los siguientes campos: ";
            if(banderaPoliza && banderaFojas && banderaLibro && banderaLicenciado && banderaCorredor)
            {
                res = RAC.actualizarDatos(noPoliza, noDeFojas, noLibro, idLicenciado, idCorredor);
                if (res > 0)
                {
                    listar();
                    limpiar();
                    
                }
            }
            else
            {
                if(!banderaPoliza)
                {
                    txtNumeroDePoliza.setText("");
                    verificar+="-" + errores[0];
                }
                if (!banderaFojas)
                {
                    txtNoDeFojas.setText("");
                    verificar += "-" + errores[1];
                }
                if (!banderaLibro)
                    verificar += "-" + errores[2];
                if(!banderaLicenciado)
                    verificar += "-" + errores[3];
                if(!banderaCorredor)
                    verificar += "-" + errores[4];

                JOptionPane.showMessageDialog(null, verificar, "Error Registro", 1);
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        PantallaPrincipal pp = new PantallaPrincipal();
        pp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActasConsRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActasConsRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActasConsRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActasConsRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActasConsRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxCorredor;
    private javax.swing.JComboBox<String> cbxLibro;
    private javax.swing.JComboBox<String> cbxLicenciado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbActasConst;
    private javax.swing.JTextField txtNoDeFojas;
    private javax.swing.JTextField txtNumeroDePoliza;
    // End of variables declaration//GEN-END:variables
}
