//Angeles Gómez Jesús Gerardo
//Peñafiel Hernández José Manuel
//Ramírez Serna Brayan Emmanuel
package Paquete_Vistas;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jesma
 */
public class RegistroSociedad extends javax.swing.JFrame {
    
    private final Paquete_Modelo.Sociedad regimenesSociales;
    public ArrayList<Paquete_Modelo.RegimenesSociales> regimenesRegistrados = new ArrayList();
    

    /**
     * Creates new form RegistroSociedad
     */
    public RegistroSociedad() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Paquete_Imagenes/128Logo.png")).getImage());
        this.setLocationRelativeTo(null);
        regimenesSociales = new Paquete_Modelo.Sociedad();
        regimenesRegistrados = regimenesSociales.generarLista();
        limpiar();
        btnActualizar.setEnabled(false);
        for(int i = 0; i < regimenesRegistrados.size(); i++)
            cbxRegimenJuridico.addItem(regimenesRegistrados.get(i).getRegimenJuridico());
    }
    
    public void limpiar()
    {
        txtDenominacion.setText("");
        txtObjetoSocial.setText("");
        txtCapital.setText("");
        cbxRegimenJuridico.setSelectedIndex(0);
    }
    
    public void listar()
    {
        tbSociedad.setModel(regimenesSociales.getDatos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDenominacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCapital = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtObjetoSocial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxRegimenJuridico = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSociedad = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(232, 232, 232));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registrar Sociedad");

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Completa la siguiente información");

        jLabel3.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Denominación:");

        txtDenominacion.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtDenominacion.setForeground(new java.awt.Color(0, 0, 0));
        txtDenominacion.setToolTipText("Denominación de la sociedad ");
        txtDenominacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDenominacionFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Capital:");

        txtCapital.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtCapital.setForeground(new java.awt.Color(0, 0, 0));
        txtCapital.setToolTipText("Capital de la sociedad ");
        txtCapital.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCapitalFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Objeto Social:");

        txtObjetoSocial.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtObjetoSocial.setForeground(new java.awt.Color(0, 0, 0));
        txtObjetoSocial.setToolTipText("Objeto Social de la sociedad ");
        txtObjetoSocial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtObjetoSocialFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Régimen Jurídico:");

        cbxRegimenJuridico.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cbxRegimenJuridico.setForeground(new java.awt.Color(0, 0, 0));
        cbxRegimenJuridico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion" }));
        cbxRegimenJuridico.setToolTipText("Régimen Jurídico de la sociedad ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/Sociedad.png"))); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/GuardarBtn.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/ActualizarBtn.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/AtrasBtn.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxRegimenJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(37, 37, 37)
                        .addComponent(btnActualizar)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addComponent(txtDenominacion)
                            .addComponent(txtObjetoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObjetoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnActualizar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxRegimenJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110))
        );

        tbSociedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSociedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSociedadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSociedad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean banderaDenominacion = true;
    boolean banderaObjetoSocial = true;
    private void txtDenominacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDenominacionFocusLost
        String denominacion = txtDenominacion.getText();
        if(denominacion.isEmpty())
            banderaDenominacion = false;
        else
            txtDenominacion.setText(denominacion.toUpperCase());
    }//GEN-LAST:event_txtDenominacionFocusLost

    private void txtCapitalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCapitalFocusLost
        
    }//GEN-LAST:event_txtCapitalFocusLost

    private void txtObjetoSocialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtObjetoSocialFocusLost
        
    }//GEN-LAST:event_txtObjetoSocialFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
       String denominacion = null, capitalS = null, objetoSocial = null;
       int res = 0, capital = 0, regimenJuridico = 0;
       boolean banderaDenominacion = true, banderaCapital = true, banderaObjetoSocial = true, banderaRegimen = true;
       
      denominacion = txtDenominacion.getText();
      if (denominacion.isEmpty())
          banderaDenominacion = false;
      
      capitalS = txtCapital.getText();
      try
      {
          capital = Integer.parseInt(capitalS);
      }
      catch (NumberFormatException e)
      {
          banderaCapital = false;
      }
      
      objetoSocial = txtObjetoSocial.getText();
      if(objetoSocial.isEmpty())
          banderaObjetoSocial = false;
      
      regimenJuridico = cbxRegimenJuridico.getSelectedIndex();
      if(regimenJuridico == 0)
          banderaRegimen = false;
      
       String errores[] = {" Denominación ", " Capital ", " Objeto Social ", " Régimen Jurídico "};
       String verificar = "Favor de Verificar los siguientes campos: ";
      
      if (banderaDenominacion && banderaCapital && banderaObjetoSocial && banderaRegimen)
      {
          res = regimenesSociales.insertarDatos(denominacion, capital, objetoSocial, regimenJuridico);
          if(res > 0)
          {
              listar();
              limpiar();
              btnGuardar.setEnabled(false);
              btnActualizar.setEnabled(true);
          }
      }
      else
      {
          if (!banderaDenominacion)
              verificar += "-" + errores[0];
          if(!banderaCapital)
          {
              verificar += "-" + errores[1];
              txtCapital.setText("");
          }
          if(!banderaObjetoSocial)
              verificar += "-" + errores[2];
          if(!banderaRegimen)
              verificar += "-" + errores[3];
          
          JOptionPane.showMessageDialog(null, verificar, "Error Registro de Sociedades", 2);
          
      }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tbSociedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSociedadMouseClicked
   
        int row = tbSociedad.getSelectedRow();
        txtDenominacion.setText((tbSociedad.getValueAt(row, 0).toString()));
        txtCapital.setText(tbSociedad.getValueAt(row, 1).toString());
        txtObjetoSocial.setText(tbSociedad.getValueAt(row, 2).toString());
        cbxRegimenJuridico.setSelectedItem(tbSociedad.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbSociedadMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       String denominacion = null, capitalS = null, objetoSocial = null;
       int res = 0, capital = 0, regimenJuridico = 0;
       boolean banderaDenominacion = true, banderaCapital = true, banderaObjetoSocial = true, banderaRegimen = true;
       
      denominacion = txtDenominacion.getText();
      if (denominacion.isEmpty())
          banderaDenominacion = false;
      
      capitalS = txtCapital.getText();
      try
      {
          capital = Integer.parseInt(capitalS);
      }
      catch (NumberFormatException e)
      {
          banderaCapital = false;
      }
      
      objetoSocial = txtObjetoSocial.getText();
      if(objetoSocial.isEmpty())
          banderaObjetoSocial = false;
      
      regimenJuridico = cbxRegimenJuridico.getSelectedIndex();
      if(regimenJuridico == 0)
          banderaRegimen = false;
      
       String errores[] = {" Denominación ", " Capital ", " Objeto Social ", " Régimen Jurídico "};
       String verificar = "Favor de Verificar los siguientes campos: ";
      
      if (banderaDenominacion && banderaCapital && banderaObjetoSocial && banderaRegimen)
      {
          res = regimenesSociales.actualizarDatos(denominacion, capital, objetoSocial, regimenJuridico);
          if(res > 0)
          {
              listar();
              limpiar();
             
          }
      }
      else
      {
          if (!banderaDenominacion)
              verificar += "-" + errores[0];
          if(!banderaCapital)
          {
              verificar += "-" + errores[1];
              txtCapital.setText("");
          }
          if(!banderaObjetoSocial)
              verificar += "-" + errores[2];
          if(!banderaRegimen)
              verificar += "-" + errores[3];
          
          JOptionPane.showMessageDialog(null, verificar, "Error Registro de Sociedades", 2);
          
      } 
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        PantallaPrincipal pp = new PantallaPrincipal();
        pp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroSociedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroSociedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroSociedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroSociedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroSociedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxRegimenJuridico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSociedad;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtDenominacion;
    private javax.swing.JTextField txtObjetoSocial;
    // End of variables declaration//GEN-END:variables
}
