//Angeles Gómez Jesús Gerardo
//Peñafiel Hernández José Manuel
//Ramírez Serna Brayan Emmanuel
package Paquete_Vistas;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jesma
 */
public class SociosRegistro extends javax.swing.JFrame {
    
    private final Paquete_Modelo.Socio RAS;
    public ArrayList<Paquete_Modelo.Nacionalidad> nacionalidades = new ArrayList();
    public ArrayList<Paquete_Modelo.Roles> roles = new ArrayList();
    public ArrayList<Paquete_Modelo.Denominaciones> denominaciones = new ArrayList();

    /**
     * Creates new form RegistroSociedad
     */
    public SociosRegistro() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Paquete_Imagenes/128Logo.png")).getImage());
        this.setLocationRelativeTo(null);
        RAS = new Paquete_Modelo.Socio();
        
        nacionalidades = RAS.generarListaNacionalidad();
        for(int i = 0; i < nacionalidades.size(); i++)
            cbxNacionalidad.addItem(nacionalidades.get(i).getNacionalidad());
        
        roles = RAS.generarListaRoles();
        for(int i = 0; i < roles.size(); i++)
            cbxRol.addItem(roles.get(i).getRol());
        
        denominaciones = RAS.generarListaDenominaciones();
        for(int i = 0; i < denominaciones.size(); i++)
            cbxDenominacion.addItem(denominaciones.get(i).getDenominacion());

        listar();
        limpiar();
        
    }
    
    public void limpiar()
    {
        txtNombre.setText("");
        txtEdad.setText("");
        txtCURP.setText("");
        txtRfc.setText("");
        txtIdmex.setText("");
        txtOcupacion.setText("");
        txtDireccion.setText("");
        cbxNacionalidad.setSelectedIndex(0);
        cbxRol.setSelectedIndex(0);
        cbxDenominacion.setSelectedIndex(0);
    }
    
    public void listar()
    {
        tbSocios.setModel(RAS.getDatos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCURP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtIdmex = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtOcupacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rbtnMasculino = new javax.swing.JRadioButton();
        rdbtnFemenino = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxNacionalidad = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        btGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbxDenominacion = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnAtras = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSocios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(232, 232, 232));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registrar Socios");

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Completa la siguiente información");

        jLabel3.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setToolTipText("Nombre del Socio a registrar");
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Edad:");

        txtEdad.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtEdad.setForeground(new java.awt.Color(0, 0, 0));
        txtEdad.setToolTipText("Edad del Socio a registrar");
        txtEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEdadFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CURP:");

        txtCURP.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtCURP.setForeground(new java.awt.Color(0, 0, 0));
        txtCURP.setToolTipText("Código Único de Registro de Población del Socio a registrar");
        txtCURP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCURPFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("RFC:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/SocioForm.png"))); // NOI18N

        txtRfc.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtRfc.setForeground(new java.awt.Color(0, 0, 0));
        txtRfc.setToolTipText("Registro Federal del Contribuyente del Socio a registrar");
        txtRfc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRfcFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("IDMEX:");

        txtIdmex.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtIdmex.setForeground(new java.awt.Color(0, 0, 0));
        txtIdmex.setToolTipText("Dígitos identificativos de la INE del Socio a registrar");
        txtIdmex.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdmexFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Ocupación");

        txtOcupacion.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtOcupacion.setForeground(new java.awt.Color(0, 0, 0));
        txtOcupacion.setToolTipText("Ocupación del Socio a registrar");
        txtOcupacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOcupacionFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Sexo");

        Sexo.add(rbtnMasculino);
        rbtnMasculino.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        rbtnMasculino.setForeground(new java.awt.Color(0, 0, 0));
        rbtnMasculino.setText("Masculino");
        rbtnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMasculinoActionPerformed(evt);
            }
        });

        Sexo.add(rdbtnFemenino);
        rdbtnFemenino.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        rdbtnFemenino.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnFemenino.setSelected(true);
        rdbtnFemenino.setText("Femenino");

        jLabel11.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Dirección");

        txtDireccion.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setToolTipText("Dirección del Socio a registrar");

        jLabel12.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nacionalidad");

        cbxNacionalidad.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cbxNacionalidad.setForeground(new java.awt.Color(0, 0, 0));
        cbxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción" }));
        cbxNacionalidad.setToolTipText("Nacionalidad del Socio a registrar");

        jLabel13.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Rol:");

        cbxRol.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cbxRol.setForeground(new java.awt.Color(0, 0, 0));
        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        cbxRol.setToolTipText("Rol que desempeñara el Socio a registrar");

        btGuardar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/GuardarBtn.png"))); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/ActualizarBtn.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Sociedad");

        cbxDenominacion.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        cbxDenominacion.setForeground(new java.awt.Color(0, 0, 0));
        cbxDenominacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una" }));
        cbxDenominacion.setToolTipText("Sociedad de la cual forma parte el Socio a registrar");
        cbxDenominacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDenominacionActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Oswald", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/EliminarBtn.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Paquete_Imagenes/AtrasBtn.png"))); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCURP)
                    .addComponent(txtRfc)
                    .addComponent(txtIdmex, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btGuardar)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnActualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminar))
                                .addComponent(jLabel12)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rbtnMasculino)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdbtnFemenino))
                                .addComponent(jLabel11)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(cbxDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras)
                        .addGap(91, 91, 91))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdmex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnMasculino)
                            .addComponent(rdbtnFemenino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(btGuardar)
                            .addComponent(btnEliminar))))
                .addGap(84, 84, 84))
        );

        tbSocios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSocios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSociosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSocios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean banderaDenominacion = true;
    boolean banderaObjetoSocial = true;
    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
       
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEdadFocusLost
        
    }//GEN-LAST:event_txtEdadFocusLost

    private void txtCURPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCURPFocusLost
        String curp = null;
        curp = txtCURP.getText();
        
        if(!curp.isEmpty())
            txtCURP.setText(curp.toUpperCase());
                
    }//GEN-LAST:event_txtCURPFocusLost

    private void tbSociosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSociosMouseClicked
        int row = tbSocios.getSelectedRow(); 
        
        txtNombre.setText(tbSocios.getValueAt(row, 0).toString());
        txtEdad.setText(tbSocios.getValueAt(row, 1).toString());
        txtCURP.setText(tbSocios.getValueAt(row, 2).toString());
        txtRfc.setText(tbSocios.getValueAt(row, 3).toString());
        txtIdmex.setText(tbSocios.getValueAt(row, 4).toString());
        txtOcupacion.setText(tbSocios.getValueAt(row, 5).toString());
        
        String sexo = tbSocios.getValueAt(row, 6).toString();
        if(sexo.equals("H"))
            rbtnMasculino.setSelected(true);
        else
            rdbtnFemenino.setSelected(true);
        
        txtDireccion.setText(tbSocios.getValueAt(row, 7).toString());
        cbxNacionalidad.setSelectedItem(tbSocios.getValueAt(row, 8).toString());
        cbxRol.setSelectedItem(tbSocios.getValueAt(row, 9).toString());
    }//GEN-LAST:event_tbSociosMouseClicked

    private void rbtnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMasculinoActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        String nombre = null, edadS = null, curp = null, rfc = null, idmex = null, ocupacion = null, sexo = null;
        String direccion = null, denominacion = null;
        int edad = 0, idNacionalidad = 0, idRol = 0;
        boolean banderaNombre = true, banderaEdad = true, banderaCurp = true, banderaRfc = true, banderaIdMex = true, banderaOcupacion = true;
        boolean banderaSexo = true, banderaDireccion = true, banderaIdNacionalidad = true, banderaIdRol = true, banderaDenominacion = true;
        
        String errores[] = {" Nombre ", " Edad ", " CURP ", " RFC ", " IDMEX ", " Ocupacion ", " Sexo ", " Dirección ", 
                            " Nacionalidad ", " Rol "};
        String verificar = "Favor de Verificar los siguientes campos: ";
        
        
        nombre = txtNombre.getText();
        if (nombre.isEmpty())
        {
            banderaNombre = false;
            verificar += "-" + errores[0];
        }
        
        edadS = txtEdad.getText();
        try
        {
            edad = Integer.parseInt(edadS);
        }
        catch (NumberFormatException e)
        {
            banderaEdad = false;
            verificar += "-" + errores[1];
        }
        if((edad < 18) || (edad > 100))
        {
            JOptionPane.showMessageDialog(null, "Los socios de una sociedad deben de haber cumplido la mayoría de edad");
            limpiar();
        }
        
        curp = txtCURP.getText();
        if(curp.isEmpty())
        {
            banderaCurp = false;
            verificar += "-" + errores[2];
        }
        
        rfc = txtRfc.getText();
        if(rfc.isEmpty())
        {
            banderaRfc = false;
            verificar += "-" + errores[3];
        }
        
        idmex = txtIdmex.getText();
        if(idmex.isEmpty())
        {
            banderaIdMex = false;
            verificar += "-" + errores[4];
        }
        
        ocupacion = txtOcupacion.getText();
        if(ocupacion.isEmpty())
        {
            banderaOcupacion = false;
            verificar += "-" + errores[5];
        }
        
        if(rbtnMasculino.isSelected())
            
            sexo = "H";
        else
            sexo = "M";
        
        direccion = txtDireccion.getText();
        if(direccion.isEmpty())
        {
            banderaDireccion = false;
            verificar += "-" + errores[7];
        }
        
        idNacionalidad = cbxNacionalidad.getSelectedIndex();
        if(idNacionalidad == 0)
        {
            banderaIdNacionalidad = false;
            verificar += "-" + errores[8];
        }
        
        idRol = cbxRol.getSelectedIndex();
        if(idRol == 0)
        {
            banderaIdRol = false;
            verificar += "-" + errores[9];
        }
        
        int denominacionIndex = cbxDenominacion.getSelectedIndex();
        if(denominacionIndex == 0)
            banderaDenominacion = false;
        else
            denominacion = cbxDenominacion.getSelectedItem().toString();
        
        
        int res = 0;
        
        if(banderaNombre && banderaEdad && banderaCurp && banderaRfc & banderaIdMex && banderaOcupacion && banderaSexo
                && banderaSexo && banderaIdNacionalidad && banderaIdRol && banderaDireccion && banderaDenominacion)
        {
            res = RAS.insertarDatos(nombre, edad, curp, rfc, idmex, ocupacion, sexo, direccion, idNacionalidad, idRol, denominacion);
            
            if(res > 0)
            {
                limpiar();
                listar();
            }
        }
        else
            JOptionPane.showMessageDialog(null, verificar, "Error Registro Socio", 2);   
    }//GEN-LAST:event_btGuardarActionPerformed

    private void txtRfcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRfcFocusLost
        String rfc = null;
        rfc = txtRfc.getText();
        
        if(!rfc.isEmpty())
            txtRfc.setText(rfc.toUpperCase());
    }//GEN-LAST:event_txtRfcFocusLost

    private void txtIdmexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdmexFocusLost
        
    }//GEN-LAST:event_txtIdmexFocusLost

    private void txtOcupacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOcupacionFocusLost
        
    }//GEN-LAST:event_txtOcupacionFocusLost

    private void cbxDenominacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDenominacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDenominacionActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    
        String nombre = null, edadS = null, curp = null, rfc = null, idmex = null, ocupacion = null, sexo = null;
        String direccion = null;
        int edad = 0, idNacionalidad = 0, idRol = 0;
        boolean banderaNombre = true, banderaEdad = true, banderaCurp = true, banderaRfc = true, banderaIdMex = true, banderaOcupacion = true;
        boolean banderaSexo = true, banderaDireccion = true, banderaIdNacionalidad = true, banderaIdRol = true;
        
        String errores[] = {" Nombre ", " Edad ", " CURP ", " RFC ", " IDMEX ", " Ocupacion ", " Sexo ", " Dirección ", 
                            " Nacionalidad ", " Rol "};
        String verificar = "Favor de Verificar los siguientes campos: ";
        
        
        nombre = txtNombre.getText();
        if (nombre.isEmpty())
        {
            banderaNombre = false;
            verificar += "-" + errores[0];
        }
        
        edadS = txtEdad.getText();
        try
        {
            edad = Integer.parseInt(edadS);
        }
        catch (NumberFormatException e)
        {
            banderaEdad = false;
            verificar += "-" + errores[1];
        }
        if((edad < 18) || (edad > 100))
        {
            JOptionPane.showMessageDialog(null, "Los socios de una sociedad deben de haber cumplido la mayoría de edad");
            limpiar();
        }
        
        curp = txtCURP.getText();
        if(curp.isEmpty())
        {
            banderaCurp = false;
            verificar += "-" + errores[2];
        }
        
        rfc = txtRfc.getText();
        if(rfc.isEmpty())
        {
            banderaRfc = false;
            verificar += "-" + errores[3];
        }
        
        idmex = txtIdmex.getText();
        if(idmex.isEmpty())
        {
            banderaIdMex = false;
            verificar += "-" + errores[4];
        }
        
        ocupacion = txtOcupacion.getText();
        if(ocupacion.isEmpty())
        {
            banderaOcupacion = false;
            verificar += "-" + errores[5];
        }
        
        if(rbtnMasculino.isSelected())
            sexo = "H";
        else
            sexo = "M";
        
        direccion = txtDireccion.getText();
        if(direccion.isEmpty())
        {
            banderaDireccion = false;
            verificar += "-" + errores[7];
        }
        
        idNacionalidad = cbxNacionalidad.getSelectedIndex();
        if(idNacionalidad == 0)
        {
            banderaIdNacionalidad = false;
            verificar += "-" + errores[8];
        }
        
        idRol = cbxRol.getSelectedIndex();
        if(idRol == 0)
        {
            banderaIdRol = false;
            verificar += "-" + errores[9];
        }
        
        String denominacion = null;
        int denominacionIndex = cbxDenominacion.getSelectedIndex();
        if(denominacionIndex == 0)
            banderaDenominacion = false;
        else
            denominacion = cbxDenominacion.getSelectedItem().toString();
        
        
        int res = 0;
        
        if(banderaNombre && banderaEdad && banderaCurp && banderaRfc & banderaIdMex && banderaOcupacion && banderaSexo
                && banderaSexo && banderaIdNacionalidad && banderaIdRol && banderaDireccion)
        {
            res = RAS.actualizarDatos(nombre, edad, curp, rfc, idmex, ocupacion, sexo, direccion, idNacionalidad, idRol, denominacion);
            
            if(res > 0)
            {
                limpiar();
                listar();
            }
        }
        else
            JOptionPane.showMessageDialog(null, verificar, "Error Registro Socio", 2);

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int res = 0;
        int row = tbSocios.getSelectedRow();
        int fila = tbSocios.getSelectedColumnCount();
        
        if (fila < 1)
            JOptionPane.showMessageDialog(null, "Favor de seleccionar un registro", "Borrar", -1);
        else
        {
            res = RAS.eliminarRegistro(tbSocios.getValueAt(row, 0).toString());
            if (res > 0)
            {
                limpiar();
                listar();
                
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        PantallaPrincipal pp = new PantallaPrincipal();
        pp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SociosRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SociosRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SociosRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SociosRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SociosRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbxDenominacion;
    private javax.swing.JComboBox<String> cbxNacionalidad;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JRadioButton rdbtnFemenino;
    private javax.swing.JTable tbSocios;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdmex;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
